#!/usr/bin/env python3
"""What `sweep.py` claims about footers and `WORK/` notes, as tests rather than
as prose.

Run: python3 -m unittest discover -s .agents/skills/sweep -p 'test_*.py'
"""
import os
import pathlib
import tempfile
import unittest

import sweep


class Footer(unittest.TestCase):
    """Every marker in AGENT_FOOTERS is current. Each agent's runtime appends
    its own and the agent does not choose it, so the sweep recognises all of
    them or it reports our own replies as USER's unanswered questions."""

    def setUp(self):
        self.setup = {
            "USER": "toumix",
            "AGENT_FOOTERS": ["claude.ai/code", "Generated by Codex"],
        }

    def comment(self, body, user="toumix"):
        return {"body": body, "user": {"login": user}}

    def test_the_shipped_config_lists_both_runtimes(self):
        self.assertEqual(sweep.config(sweep.CONFIG)["AGENT_FOOTERS"],
                         ["claude.ai/code", "Generated by Codex"])

    def test_a_bare_marker_on_the_last_line_answers(self):
        self.assertTrue(sweep.answered(
            self.comment("Done.\n\nGenerated by Codex"), self.setup))

    def test_a_link_label_never_answers_however_exactly_it_reads(self):
        """The label is the half a human types and the target is the half the
        runtime emits, so a matching label over any destination would let a
        comment silence its own thread."""
        self.assertFalse(sweep.answered(self.comment(
            "Done.\n\n[Generated by Codex](https://anywhere-at-all.example)"),
            self.setup))

    def test_a_runtime_wanting_a_linked_footer_lists_its_url_token(self):
        self.assertTrue(sweep.answered(self.comment(
            "Done.\n\n[Generated by Codex](https://chatgpt.com/share/example)"),
            {**self.setup, "AGENT_FOOTERS": [*self.setup["AGENT_FOOTERS"],
                                             "chatgpt.com/share"]}))

    def test_a_url_marker_inside_the_link_target_answers(self):
        """Claude Code's mandated footer, which no Claude session can opt out
        of: the marker is a fragment of the href, wrapped in emphasis."""
        self.assertTrue(sweep.answered(self.comment(
            "Done.\n\n_Generated by [Claude Code](https://claude.ai/code)_"),
            self.setup))

    def test_a_session_id_in_the_target_still_answers(self):
        self.assertTrue(sweep.answered(self.comment(
            "Done.\n\n_Generated by [Claude Code]"
            "(https://claude.ai/code/session_01U5t8qLxoQZ6VHAuEDoU6zm)_"),
            self.setup))

    def test_a_marker_in_prose_does_not_answer(self):
        self.assertFalse(sweep.answered(self.comment(
            "This line mentions Generated by Codex in prose."), self.setup))

    def test_a_marker_must_be_on_the_final_line(self):
        self.assertFalse(sweep.answered(self.comment(
            "Generated by Codex\nA later human-authored line."), self.setup))

    def test_an_empty_marker_never_matches(self):
        self.assertFalse(sweep.agent_footer(
            "A human-authored line.", {"AGENT_FOOTERS": ["", "  "]}))

    def test_no_footers_configured_matches_nothing(self):
        self.assertFalse(sweep.agent_footer("Generated by Codex", {}))

    def test_anyone_but_USER_always_answers(self):
        self.assertTrue(sweep.answered(
            self.comment(None, user="toumix-agents"), self.setup))

    def test_a_body_USER_wrote_with_no_footer_is_unanswered(self):
        self.assertFalse(sweep.answered(
            self.comment("what did Evening do?"), self.setup))


class Stale(unittest.TestCase):
    """A note carries the date it was read, so staleness is arithmetic rather
    than discipline — the drift no amount of "remember to check" ever fixed."""

    def test_a_note_read_after_its_item_moved_is_current(self):
        self.assertEqual(sweep.stale({489: "2026-09-01"},
                                     {489: "2026-08-30T12:00:00Z"}), [])

    def test_same_day_is_current_whatever_the_hour(self):
        self.assertEqual(sweep.stale({489: "2026-09-01"},
                                     {489: "2026-09-01T23:59:59Z"}), [])

    def test_an_item_that_moved_a_day_later_is_stale(self):
        self.assertEqual(sweep.stale({489: "2026-08-31"},
                                     {489: "2026-09-01T00:00:01Z"}), [489])

    def test_a_note_with_no_readable_date_cannot_say_when_it_was_true(self):
        self.assertEqual(sweep.stale({489: None},
                                     {489: "2026-09-01T00:00:00Z"}), [489])

    def test_a_note_whose_item_is_not_open_is_not_stale_but_orphan(self):
        self.assertEqual(sweep.stale({676: "2020-01-01"}, {}), [])


class Cited(unittest.TestCase):
    """Forming a view on one item pulls in what it references: that is how an
    issue earns a note without a human deciding it has."""

    def test_numbers_are_read_out_of_prose(self):
        self.assertEqual(sweep.cited(["waits on #625, blocks #443"]),
                         {625, 443})

    def test_every_note_contributes(self):
        self.assertEqual(sweep.cited(["#1", "#2 and #1"]), {1, 2})

    def test_a_note_citing_nothing_pulls_in_nothing(self):
        self.assertEqual(sweep.cited(["no numbers here"]), set())


class Notes(unittest.TestCase):
    """`notes` is the whole rule: one file per open item, deleted when the
    item is not open any more."""

    def test_agreement_is_silent(self):
        self.assertEqual(sweep.notes({489, 443}, {443, 489}), ([], []))

    def test_an_item_with_no_note_is_missing(self):
        self.assertEqual(sweep.notes({489}, {489, 443}), ([443], []))

    def test_a_note_with_no_open_item_is_an_orphan(self):
        self.assertEqual(sweep.notes({489, 676}, {489}), ([], [676]))

    def test_both_at_once_and_sorted(self):
        self.assertEqual(sweep.notes({9, 2}, {3, 1}), ([1, 3], [2, 9]))

    def test_nothing_open_makes_every_note_an_orphan(self):
        self.assertEqual(sweep.notes({1, 2}, set()), ([], [1, 2]))


class MemoryClone(unittest.TestCase):
    """A sweep run without the memory clone beside it says so, rather than
    reporting every open item as missing its note."""

    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = pathlib.Path(self.directory.name)
        self.setup = {"MEMORY_REPO": "someone/memory"}

    def override(self, path):
        os.environ["AGENTS_MEMORY"] = str(path)
        self.addCleanup(os.environ.pop, "AGENTS_MEMORY", None)

    def test_a_clone_carrying_WORK_is_found(self):
        (self.root / "WORK").mkdir()
        self.override(self.root)
        self.assertEqual(sweep.memory_clone(self.setup), self.root)

    def test_a_directory_without_WORK_is_not_a_memory_clone(self):
        self.override(self.root)
        self.assertIsNone(sweep.memory_clone(self.setup))

    def test_a_path_that_does_not_exist_is_none(self):
        self.override(self.root / "nowhere")
        self.assertIsNone(sweep.memory_clone(self.setup))


class Config(unittest.TestCase):
    """`config.env` is the one file naming USER, AGENT and the repos, so a
    malformed line raises rather than parsing to a key nobody reads."""

    def parse(self, text):
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        path = pathlib.Path(directory.name) / "config.env"
        path.write_text(text)
        return sweep.config(path)

    def test_values_keep_everything_after_the_first_equals(self):
        self.assertEqual(self.parse("AGENT_EMAIL=a=b@c\n")["AGENT_EMAIL"],
                         "a=b@c")

    def test_work_repos_is_a_list(self):
        self.assertEqual(self.parse("WORK_REPOS=a/b,c/d\n")["WORK_REPOS"],
                         ["a/b", "c/d"])

    def test_footers_are_a_list_and_keep_their_spaces(self):
        self.assertEqual(
            self.parse("AGENT_FOOTERS=claude.ai/code,Generated by Codex\n")
            ["AGENT_FOOTERS"], ["claude.ai/code", "Generated by Codex"])

    def test_an_empty_footer_entry_is_dropped(self):
        self.assertEqual(self.parse("AGENT_FOOTERS=a,, ,b\n")["AGENT_FOOTERS"],
                         ["a", "b"])

    def test_adopted_prs_maps_repo_to_numbers(self):
        self.assertEqual(self.parse("ADOPTED_PRS=a/b:1,2 c/d:3\n")
                         ["ADOPTED_PRS"], {"a/b": [1, 2], "c/d": [3]})

    def test_an_empty_adopted_prs_is_no_repo(self):
        self.assertEqual(self.parse("ADOPTED_PRS=\n")["ADOPTED_PRS"], {})

    def test_comments_and_blank_lines_are_skipped(self):
        """The seed in `template/memory/config.env` ships commented, and the
        file is edited by hand, so a `#` line is not a malformed setting."""
        self.assertEqual(self.parse(
            "# what this file is\n\nUSER=toumix\n  # indented\nAGENT=agents\n"),
            {"USER": "toumix", "AGENT": "agents"})

    def test_a_hash_inside_a_value_is_kept(self):
        self.assertEqual(self.parse("APPROVE_EMOJI=rocket # not a comment\n")
                         ["APPROVE_EMOJI"], "rocket # not a comment")

    def test_a_line_with_no_key_raises(self):
        with self.assertRaises(ValueError):
            self.parse("USER=toumix\nnot a setting\n")


if __name__ == "__main__":
    unittest.main()
